---
- name: ensure nginx is at the latest version
  apt: name=nginx-full state=latest
  notify:
    - restart nginx
  tags: [nginx]

- name: install nginx config file
  template:
    src: "{{ app_name }}.j2"
    dest: "/etc/nginx/sites-available/{{ app_name }}.conf"
    backup: yes
  notify:
    - restart nginx
  tags: [configuration,nginx]

- name: Ensure that the default site is disabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx

- name: Ensure that the app location site is enabled
  file:
    src: /etc/nginx/sites-available/{{ app_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ app_name }}.conf
    state: link
  notify:
    - restart nginx
