---

- name: Create the user 'deployer'
  user:
    name: "{{ system_user }}"
    comment: Deployer
    groups: sudo,www-data
    shell: /bin/bash

- name: "Set password for the '{{ system_user }}'"
  command: "echo \"1234\" | passwd --stdin {{ system_user }}"

- name: ensure private key and public one are present
  copy:
    src: "{{ item }}"
    dest: "{{ user_path }}/.ssh/"
    mode: 0600
  with_items:
    - "~/.ssh/id_rsa.pub"
    - "~/.ssh/id_rsa"
  become: yes
  become_user: "{{ system_user }}"
