---
- include_tasks: universe.yml

- name: Generate locale {{ locale }}
  command: /usr/sbin/locale-gen {{ locale }}

- name: Set locale {{ locale }}
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }} LANGUAGE={{ language }}

- name: Set timezone (/etc/timezone)
  template: src=timezone dest=/etc/timezone
  notify: update tzdata

- name: Install common packages
  apt:
    name:
      - ntp
      - git
      - unattended-upgrades
    state: present

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Upgrade APT to the latest packages
  apt:
    upgrade: safe
